### ISSUE TITLE
Fragment links

### ISSUE THREAD

**Issue by KamasamaK** [foundeo/cfdocs#769]
I'm not sure if this is a supported use case, but when navigating to a particular parameter via fragment identifier (e.g. [cfargument#required](https://cfdocs.org/cfargument#p-required)) the header bar obscures part of the parameter definition.

**Comment by pfreitag** [comment]
Yeah, I would like to see that working better... I'm not sure how to fix that other than hiding the header bar - do you have any ideas?

**Comment by KamasamaK** [comment]
You can play around with the values, but adding something like this to the CSS should work

```css
:target::before {
	content: "";
	display: block;
	margin-top: -50px;
	height: 50px;
	width: 1px
}
```
